# Generated by Django 6.0.4 on 2026-05-16 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('GRADE_1', '1年'), ('GRADE_2', '2年'), ('GRADE_3', '3年')], max_length=20)),
                ('semester_type', models.CharField(choices=[('TWO', '2学期制'), ('THREE', '3学期制')], max_length=20)),
                ('start_date', models.DateField()),
                ('test_date', models.DateField(blank=True, null=True)),
                ('tutoring_days', models.JSONField(blank=True, default=list, verbose_name='指導曜日')),
            ],
        ),
        migrations.CreateModel(
            name='UnitMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('MATH', '数学'), ('ENGLISH', '英語')], max_length=20)),
                ('grade', models.CharField(choices=[('GRADE_1', '1年'), ('GRADE_2', '2年'), ('GRADE_3', '3年')], max_length=20)),
                ('unit_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '未着手'), (1, '着手'), (2, '進行中'), (3, '完了')], default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='macrotutor.student')),
                ('unit_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macrotutor.unitmaster')),
            ],
        ),
    ]
